# .github/workflows/deploy.yml
name: Deploy Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::214117827798:role/ExperimentationPlatform-CICD-Dev
          aws-region: us-west-2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd infrastructure
          npm install
          
      - name: CDK Deploy
        run: |
          cd infrastructure
          npx cdk deploy --all --require-approval never

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: deploy-dev
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::214117827798:role/ExperimentationPlatform-CICD-Staging
          aws-region: us-west-2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd infrastructure
          npm install
          
      - name: CDK Deploy
        run: |
          cd infrastructure
          ENVIRONMENT=staging npx cdk deploy --all --require-approval never
